jobs:
  build:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt install netcat && ssh -R myalias:6698:localhost:6698 serveo.net &
      - run: sudo nc -l -p 6698
