jobs:
  build:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt install netcat
      - run: sudo nc -l -p 6698 &
      - run: ssh -o StrictHostKeyChecking=no -R 6698:localhost:6698 serveo.net
